services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: track_my_subs_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: track_my_subs_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
